package com.astroboy.family.GreenDao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.astroboy.family.GreenDao.User;
import com.astroboy.family.GreenDao.Family;

import com.astroboy.family.GreenDao.UserDao;
import com.astroboy.family.GreenDao.FamilyDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig familyDaoConfig;

    private final UserDao userDao;
    private final FamilyDao familyDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        familyDaoConfig = daoConfigMap.get(FamilyDao.class).clone();
        familyDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        familyDao = new FamilyDao(familyDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(Family.class, familyDao);
    }
    
    public void clear() {
        userDaoConfig.getIdentityScope().clear();
        familyDaoConfig.getIdentityScope().clear();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public FamilyDao getFamilyDao() {
        return familyDao;
    }

}
