package com.astroboy.family.GreenDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table FAMILY.
 */
public class Family {

    private Long id;
    private int FM_ID;
    private int User_ID;
    private String FM_Name;
    private String FM_Address;
    private String Create_Time;
    private String Reserved_Tel;
    private Integer Member_Type;
    private Integer Member_ID;

    public Family() {
    }

    public Family(Long id) {
        this.id = id;
    }

    public Family(Long id, int FM_ID, int User_ID, String FM_Name, String FM_Address, String Create_Time, String Reserved_Tel, Integer Member_Type, Integer Member_ID) {
        this.id = id;
        this.FM_ID = FM_ID;
        this.User_ID = User_ID;
        this.FM_Name = FM_Name;
        this.FM_Address = FM_Address;
        this.Create_Time = Create_Time;
        this.Reserved_Tel = Reserved_Tel;
        this.Member_Type = Member_Type;
        this.Member_ID = Member_ID;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getFM_ID() {
        return FM_ID;
    }

    public void setFM_ID(int FM_ID) {
        this.FM_ID = FM_ID;
    }

    public int getUser_ID() {
        return User_ID;
    }

    public void setUser_ID(int User_ID) {
        this.User_ID = User_ID;
    }

    public String getFM_Name() {
        return FM_Name;
    }

    public void setFM_Name(String FM_Name) {
        this.FM_Name = FM_Name;
    }

    public String getFM_Address() {
        return FM_Address;
    }

    public void setFM_Address(String FM_Address) {
        this.FM_Address = FM_Address;
    }

    public String getCreate_Time() {
        return Create_Time;
    }

    public void setCreate_Time(String Create_Time) {
        this.Create_Time = Create_Time;
    }

    public String getReserved_Tel() {
        return Reserved_Tel;
    }

    public void setReserved_Tel(String Reserved_Tel) {
        this.Reserved_Tel = Reserved_Tel;
    }

    public Integer getMember_Type() {
        return Member_Type;
    }

    public void setMember_Type(Integer Member_Type) {
        this.Member_Type = Member_Type;
    }

    public Integer getMember_ID() {
        return Member_ID;
    }

    public void setMember_ID(Integer Member_ID) {
        this.Member_ID = Member_ID;
    }

    @Override
    public String toString() {
        return "Family{" +
                "id=" + id +
                ", FM_ID=" + FM_ID +
                ", User_ID=" + User_ID +
                ", FM_Name='" + FM_Name + '\'' +
                ", FM_Address='" + FM_Address + '\'' +
                ", Create_Time='" + Create_Time + '\'' +
                ", Reserved_Tel='" + Reserved_Tel + '\'' +
                ", Member_Type=" + Member_Type +
                ", Member_ID=" + Member_ID +
                '}';
    }
}
