package com.astroboy.family.GreenDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table USER.
 */
public class User {

    private Long id;
    private int User_ID;
    /** Not-null value. */
    private String User_Name;
    /** Not-null value. */
    private String User_Password;
    private String User_Address;
    /** Not-null value. */
    private String User_Phone;
    private String User_Identity;
    private String User_Mail;
    private String User_Sex;
    private String User_RealName;
    private String User_Age;
    private String User_Hobby;
    private String User_Blood;

    public User() {
    }

    public User(Long id) {
        this.id = id;
    }

    public User(Long id, int User_ID, String User_Name, String User_Password, String User_Address, String User_Phone, String User_Identity, String User_Mail, String User_Sex, String User_RealName, String User_Age, String User_Hobby, String User_Blood) {
        this.id = id;
        this.User_ID = User_ID;
        this.User_Name = User_Name;
        this.User_Password = User_Password;
        this.User_Address = User_Address;
        this.User_Phone = User_Phone;
        this.User_Identity = User_Identity;
        this.User_Mail = User_Mail;
        this.User_Sex = User_Sex;
        this.User_RealName = User_RealName;
        this.User_Age = User_Age;
        this.User_Hobby = User_Hobby;
        this.User_Blood = User_Blood;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getUser_ID() {
        return User_ID;
    }

    public void setUser_ID(int User_ID) {
        this.User_ID = User_ID;
    }

    /** Not-null value. */
    public String getUser_Name() {
        return User_Name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUser_Name(String User_Name) {
        this.User_Name = User_Name;
    }

    /** Not-null value. */
    public String getUser_Password() {
        return User_Password;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUser_Password(String User_Password) {
        this.User_Password = User_Password;
    }

    public String getUser_Address() {
        return User_Address;
    }

    public void setUser_Address(String User_Address) {
        this.User_Address = User_Address;
    }

    /** Not-null value. */
    public String getUser_Phone() {
        return User_Phone;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUser_Phone(String User_Phone) {
        this.User_Phone = User_Phone;
    }

    public String getUser_Identity() {
        return User_Identity;
    }

    public void setUser_Identity(String User_Identity) {
        this.User_Identity = User_Identity;
    }

    public String getUser_Mail() {
        return User_Mail;
    }

    public void setUser_Mail(String User_Mail) {
        this.User_Mail = User_Mail;
    }

    public String getUser_Sex() {
        return User_Sex;
    }

    public void setUser_Sex(String User_Sex) {
        this.User_Sex = User_Sex;
    }

    public String getUser_RealName() {
        return User_RealName;
    }

    public void setUser_RealName(String User_RealName) {
        this.User_RealName = User_RealName;
    }

    public String getUser_Age() {
        return User_Age;
    }

    public void setUser_Age(String User_Age) {
        this.User_Age = User_Age;
    }

    public String getUser_Hobby() {
        return User_Hobby;
    }

    public void setUser_Hobby(String User_Hobby) {
        this.User_Hobby = User_Hobby;
    }

    public String getUser_Blood() {
        return User_Blood;
    }

    public void setUser_Blood(String User_Blood) {
        this.User_Blood = User_Blood;
    }

}
